name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: sre-lab-489313
  IMAGE: sre-observability-app
  REPO: sre-repo
  REGION: us-central1
  CLUSTER: sre-cluster
  ZONE: us-central1-a

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Authenticate GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: gcloud auth configure-docker $REGION-docker.pkg.dev

      - name: Build Image
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:${{ github.sha }} .

      - name: Push Image
        run: |
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:${{ github.sha }}

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials $CLUSTER --zone $ZONE --project $PROJECT_ID

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/sre-app \
          sre-app=$REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:${{ github.sha }}
