name: Deploy to GKE

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: sre-lab-489313
      CLUSTER_NAME: sre-cluster
      CLUSTER_ZONE: us-central1-a
      IMAGE: sre-observability-app
      REPOSITORY: sre-repo
      REGION: us-central1

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/1056238819180/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions@sre-lab-489313.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:${{ github.sha }}

      - name: Install GKE auth plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials $CLUSTER_NAME \
          --zone $CLUSTER_ZONE \
          --project $PROJECT_ID

      - name: Update deployment image
        run: |
          kubectl set image deployment/sre-app \
          sre-app=$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:${{ github.sha }}

      - name: Deploy manifests
        run: |
          kubectl apply -f k8s/
